services:
  # Asigna un nombre fijo al contenedor para identificarlo fácilmente.
  react-app:
    build:
      # 'context: .' indica que el contexto de construcción es el directorio actual.
      context: .
      # Especifica el archivo que se usará para construir la imagen.
      dockerfile: Dockerfile

 # Mapeo de puertos en formato "Host:Contenedor".
    ports:
      - "8888:8888"
    volumes:
      # 1. Mapea tu código local al contenedor para la persistencia y Hot Reload
      - .:/app
      # 2. Protege los node_modules del contenedor para que no los pise tu entorno local
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true # Opcional: ayuda a Vite a detectar cambios en algunos entornos Linux