version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      # 1. Mapea tu código local al contenedor para la persistencia y Hot Reload
      - .:/app
      # 2. Protege los node_modules del contenedor para que no los pise tu entorno local
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true # Opcional: ayuda a Vite a detectar cambios en algunos entornos Linux